%% channel model

function [isopath, channel,tgt,tgtplat]=channel_model(SP, TS, locx, locy)
    isopath = phased.IsoSpeedUnderwaterPaths(...
          'ChannelDepth',SP.channelDepth,...
          'NumPathsSource','Property',...
          'NumPaths',SP.numPaths,...
          'PropagationSpeed',SP.propSpeed,...
          'BottomLoss',0.5,...
          'TwoWayPropagation',true);
    channel = phased.MultipathChannel('OperatingFrequency',SP.fc);
    % the target strength information is injected here
    tgt= phased.BackscatterSonarTarget('TSPattern',TS*ones(181,361));
    tgtplat = phased.Platform('InitialPosition',[locx;locy; -15],'Velocity',[0; 0; 0]);
end
